export const USERS_SERVICE = 'USERS_SERVICE';
export const AUTH_SERVICE = 'AUTH_SERVICE';
export const POSTS_SERVICE = 'POSTS_SERVICE';
export const COMMENTS_SERVICE = 'COMMENTS_SERVICE';
export const LIKES_SERVICE = 'LIKES_SERVICE';